### ISSUE TITLE
Spectral entropy similarity score

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsCoreUtils#116]
Add the *spectral entropy* from this [publication](https://www.nature.com/articles/s41592-021-01331-z) and based on the code from the Python package [SpectralEntropy](https://github.com/YuanyueLi/SpectralEntropy) and their examples.

This builds on the work provided by @mar-garcia with PR #115 .

**Comment by jorainer** [comment]
Merging/matching of peaks between the two spectra is described [here](https://github.com/YuanyueLi/SpectralEntropy/blob/master/spectral_entropy/tools.py#L137-L188).

basically, the code looks like an outer join with the merged spectrum keeping all peaks, but with 0 intensities in the spectrum in which the peak was not present.

**Comment by jorainer** [comment]
Reproducing how spectral entropy is implemented (based on their [python code](https://github.com/YuanyueLi/SpectralEntropy/tree/master/spectral_entropy) ):

```r
x = rbind(c(69.071, 7.917962), c(86.066, 1.021589), c(86.0969, 100.0))
y = rbind(c(41.04, 37.16), c(69.07, 66.83), c(86.1, 999.0))
colnames(x) <- c("mz", "intensity")
colnames(y) <- c("mz", "intensity")

x
          mz  intensity
[1,] 69.0710   7.917962
[2,] 86.0660   1.021589
[3,] 86.0969 100.000000

y
        mz intensity
[1,] 41.04     37.16
[2,] 69.07     66.83
[3,] 86.10    999.00

```

The python function does implicit spectra cleaning and/or standardization. The spectra cleaning first *centroids* the spectra (I would rather call that *reduce* or *fuse*) by summing intensities of peaks with an m/z smaller than a threshold (and replacing their m/z with the intensity weighted mean). Then *noise* peaks are removed, that are defined as all peaks with an intensity lower than `noise_removal` of the max intensity (default `noise_removal = 0.01`). At last the intensities are *standardized* so that the sum of all peaks is 1. To do that in R:

```r
#' function to "centroid"/fuse peaks within a spectrum. For peaks grouped
#' based on their m/z values it aggregates the intensities with `intensityFun`
#' and calculates the m/z based on an intensity weighted mean. Because this
#' function subsets the peak matrix `x` it would in general even support
#' additional columns with peak variables. For each peak group the additional
#' peak variables for the peak with the highest intensity are returned.
.peaks_fuse <- function(x, tolerance = 0, ppm = 10,
                        intensityFun = base::sum, ...) {
    grps <- group(x[, "mz"], tolerance = tolerance, ppm = ppm)
    l <- length(grps)
    if (l == grps[l])
        x
    else {
        xl <- lapply(split.data.frame(x, f = grps, drop = FALSE),
                     function(z, ifun) {
                         if (nrow(z) > 1) {
                             ints <- z[, "intensity"]
                             tmp <- z[which.max(ints), , drop = FALSE]
                             tmp[1L, "mz"] <- weighted.mean(z[, "mz"], ints)
                             tmp[1L, "intensity"] <- ifun(ints)
                             tmp
                         } else z
                     }, ifun = intensityFun)
        do.call(base::rbind, xl)
    }
}

## *centroid*/fuse peaks
x2 <- .peaks_fuse(x, tolerance = 0.05, ppm = 0)
y2 <- .peaks_fuse(y, tolerance = 0.05, ppm = 0)

x2
           mz  intensity
[1,] 69.07100   7.917962
[2,] 86.09659 101.021589

y2
        mz intensity
[1,] 41.04     37.16
[2,] 69.07     66.83
[3,] 86.10    999.00


## Remove noise peaks
.int_fun <- function(x, prop = 0.01) x >= max(x) * prop
x2 <- Spectra:::.peaks_filter_intensity_function(x2, 2L, .int_fun,
                                                 msLevel = 2L, prop = 0.01)
y2 <- Spectra:::.peaks_filter_intensity_function(y2, 2L, .int_fun,
                                                 msLevel = 2L, prop = 0.01)

x2
           mz  intensity
[1,] 69.07100   7.917962
[2,] 86.09659 101.021589

y2
        mz intensity
[1,] 41.04     37.16
[2,] 69.07     66.83
[3,] 86.10    999.00
```

Spectra are then standardized

```r
## Standardize spectrum
x2[, 2] <- x2[, 2] / sum(x2[, 2])
y2[, 2] <- y2[, 2] / sum(y2[, 2])

x2
           mz  intensity
[1,] 69.07100 0.07268216
[2,] 86.09659 0.92731784

y2
        mz  intensity
[1,] 41.04 0.03369024
[2,] 69.07 0.06058985
[3,] 86.10 0.90571991

```

This was the "preprocessing". Peaks between the two spectra are then matched.

```r
xy <- joinPeaks(x2, y2, type = "outer", ppm = 0, tolerance = 0.05)
xy
$x
           mz  intensity
[1,]       NA         NA
[2,] 69.07100 0.07268216
[3,] 86.09659 0.92731784

$y
        mz  intensity
[1,] 41.04 0.03369024
[2,] 69.07 0.06058985
[3,] 86.10 0.90571991

```

The outer join seems to be important to consider all peaks from both spectra, not just the matching ones. The entropy score is then calculated on the intensities (only).

```r
xi <- xy$x[, 2]
yi <- xy$y[, 2]
xi[is.na(xi)] <- 0
yi[is.na(yi)] <- 0

ex <- entropy(xi[xi > 0])                  # entropy of x
ey <- entropy(yi[yi > 0])                  # entropy of y

```

In the python code there is some tweaks if the entropy of either `x` or `y` is smaller than 3: [code](https://github.com/YuanyueLi/SpectralEntropy/blob/master/spectral_entropy/spectral_entropy.py#L57-L63).

```r
## If entropy is smaller 3:
if (ex < 3) {
    w <- 0.25 + 0.25 * ex
    xi <- xi^w
    xi <- xi / sum(xi)
    ex <- entropy(xi[xi > 0])
}
if (ey < 3) {
    w <- 0.25 + 0.25 * ey
    yi <- yi^w
    yi <- yi / sum(yi)
    ey <- entropy(yi[yi > 0])
}
```

Now we calculate the final score:

```r
exy <- entropy(xi + yi)                 # entropy of merged spectra
res <- 1 - (2 * exy - ex - ey) / log(4)
res
[1] 0.8984398
```

This does however not match the value of the example:  0.9826668790176113.

If we run it without the re-weighting if entropy is smaller 3 (which is the case for both):

```r
xi <- xy$x[, 2]
yi <- xy$y[, 2]
xi[is.na(xi)] <- 0
yi[is.na(yi)] <- 0

ex <- entropy(xi[xi > 0])               # entropy of x
ey <- entropy(yi[yi > 0])               # entropy of y
exy <- entropy(xi + yi)                 # entropy of merged spectra

res <- 1 - (2 * exy - ex - ey) / log(4)
res
[1] 0.9826668
```

Which is not identical to their result, but equal (with a tolerance of 0.0000001).

**Comment by jorainer** [comment]
Note: the example with the reference is [here](https://github.com/YuanyueLi/SpectralEntropy/blob/master/example.ipynb)

**Comment by jorainer** [comment]
All good - the *unweighted entropy* from the example results in a entropy similarity of 0.9826668790176113 which matches the second value from above (without weighting) and the *entropy* method in a value of 0.8984398591079145 which matches the result from our first approach, with weighting.

**Comment by jorainer** [comment]
I will now think how to best/easiest implement this.

**Comment by YuanyueLi** [comment]
Hi, I'm the author of package [SpectralEntropy](https://github.com/YuanyueLi/SpectralEntropy). Now I have wrote a R package called [MSEntropy](https://github.com/YuanyueLi/MSEntropy) to provide the function to calculate entropy simliarity, you can find the reference [here](https://cran.r-project.org/web/packages/msentropy/msentropy.pdf).

You can integrate it to the `MsCoreUtils` package directly.

Here is the example:
``` R
library(msentropy)

# Peaks A
mz_a <- c(169.071, 186.066, 186.0769)
intensity_a <- c(7.917962, 1.021589, 100.0)
peaks_a <- matrix(c(mz_a, intensity_a), ncol = 2, byrow = FALSE)

# Peaks B
mz_b <- c(120.212, 169.071, 186.066)
intensity_b <- c(37.16, 66.83, 999.0)
peaks_b <- matrix(c(mz_b, intensity_b), ncol = 2, byrow = FALSE)

# Calculate entropy similarity
entropy_similarity <- calculate_entropy_similarity(peaks_a, peaks_b, ms2_tolerance_in_da = 0.02)
```

**Comment by sgibb** [comment]
Dear @YuanyueLi thanks for this contribution! 
I just briefly looked at your code. Do you really need `Rcpp`? We try to keep the dependencies as low as possible and as far as I can see your code is pure `C` and just method registration was done by `Rcpp` (the autogenerated `RccpExport.cpp`). Would it be possible to do the method definition/registration manually/without `Rcpp`? Or did I overlooked some import pieces?

**Comment by jorainer** [comment]
I think it would be best to enable users to directly use the spectra similarity scores from `msentropy` in the `compareSpectra` function of the `Spectra` package - thus we don't need to import or depend on `msentropy`. I'll have a look how to best do that.

**Comment by YuanyueLi** [comment]
> Dear @YuanyueLi thanks for this contribution! I just briefly looked at your code. Do you really need `Rcpp`? We try to keep the dependencies as low as possible and as far as I can see your code is pure `C` and just method registration was done by `Rcpp` (the autogenerated `RccpExport.cpp`). Would it be possible to do the method definition/registration manually/without `Rcpp`? Or did I overlooked some import pieces?

Hi @sgibb, I am not very familiar with `Rccp` and R development as well. I will try to see is there any chance to remove the `Rcpp` dependencies.

**Comment by jorainer** [comment]
Closing this issue because there is no need anymore to implement that score ourself but rather use the implementation from `msentropy`.

**Comment by jorainer** [comment]
OK, I found now the problem. @cbroeckl , you were using `FUN = msentropy::msentropy_similarity` but also used the default `MAP = joinPeaks()` for the peak matching between query and target. The `msentropy::msentropy_similarity()` function does however both, matching peaks **and** calculate similarity (and in addition also clean the spectra). To use the *msentropy* similarity calculations you **must** set `MAP = joinPeaksNone()` to avoid doing the peak matching twice.

To maybe explain better what happens:

```r
library(MetaboAnnotation)
library(Spectra)
library(msdata)
library(msentropy)
fl <- system.file("TripleTOF-SWATH", "PestMix1_DDA.mzML", package = "msdata")
pest_ms2 <- filterMsLevel(Spectra(fl), 2L)
load(system.file("extdata", "minimb.RData", package = "MetaboAnnotation"))

exp.spectra <- pest_ms2[1681]
lib.spectra <- minimb[6]
```

The `joinPeaks()` function with your settings will result in:

```r
m <- joinPeaks(peaksData(exp.spectra)[[1L]],
               peaksData(lib.spectra)[[1L]],
               ppm = 0,
               tolerance = 0)
> m
$x
             mz   intensity
 [1,]  57.07345  0.02968304
 [2,]  74.09680  0.39075869
 [3,]  83.03207  0.08950645
 [4,]  97.04401  0.42991149
 [5,]        NA          NA
 [6,] 109.04526  0.58173662
 [7,] 123.02425  0.19611219
 [8,]        NA          NA
 [9,] 124.05540  6.89255524
[10,] 124.58125  0.04385486
[11,]        NA          NA
[12,] 132.04355  0.13544826
[13,]        NA          NA
[14,] 134.03769  0.20469949
[15,]        NA          NA
[16,] 134.04381  0.04549015
[17,] 136.05367  0.02291482
[18,] 137.06049  0.06899836
[19,]        NA          NA
[20,] 150.07339  0.09626607
[21,] 151.59137  0.30234459
[22,]        NA          NA
[23,] 152.05052 14.08226871
[24,] 152.08618  1.53930533
[25,]        NA          NA
[26,]        NA          NA
[27,] 166.10028  0.13925481
[28,]        NA          NA
[29,] 194.09621  2.34010577
[30,]        NA          NA
[31,] 364.06650  0.07496900

$y
            mz intensity
 [1,]       NA        NA
 [2,]       NA        NA
 [3,]       NA        NA
 [4,]       NA        NA
 [5,] 109.0446      3636
 [6,]       NA        NA
 [7,]       NA        NA
 [8,] 124.0551    349840
 [9,]       NA        NA
[10,]       NA        NA
[11,] 125.0391      2300
[12,]       NA        NA
[13,] 132.0437      3020
[14,]       NA        NA
[15,] 134.0393      3820
[16,]       NA        NA
[17,]       NA        NA
[18,]       NA        NA
[19,] 137.0622      2516
[20,]       NA        NA
[21,]       NA        NA
[22,] 152.0498    408512
[23,]       NA        NA
[24,]       NA        NA
[25,] 152.0865     67240
[26,] 153.0895      5908
[27,]       NA        NA
[28,] 166.1019      4000
[29,]       NA        NA
[30,] 194.0970      9532
[31,]       NA        NA
```

this is supposed to be the matched peak matrices - for that example, in fact, no peak from the query can be matched to any peak in the target. This are also the peak matrices that are passed along to `FUN`. For similarity functions, such as `ndotproduct()` this is fine - they expect such matched peak matrices, i.e. the peak matrices having the same number of rows, with peaks considered matching being in the same row. However, `msentropy_similarity()` seems to have a problem with this particular (non matching) peaks.

So, it is very important to use `MAP = joinPeaksNone` with *msentropy* (similarly, if you want to use GNPS-based similarity scores, you must use `MAP = joinPeaksGnps`):

```r
csp <- CompareSpectraParam(
    MAPFUN = joinPeaksNone,
    tolerance = 0,
    ppm = 5,
    FUN = msentropy::msentropy_similarity,
    requirePrecursor = TRUE,
    requirePrecursorPeak = FALSE,
    THRESHFUN = function(x) which(x >= 0.5),
    toleranceRt = Inf,
    percentRt = 0
)
system.time(
    d <- matchSpectra(exp.spectra,
                      lib.spectra,
                      param = csp,
                      rtColname = c("rtime", "rtime"),
                      BPPARAM = SerialParam(),
                      addOriginalQueryIndex = TRUE)
)
   user  system elapsed 
  0.053   0.000   0.054 
d$score
[1] 0.8100979
```

Another important thing: `msentropy_similarity()` has different parameters to specify the ppm and tolerance! So, the `ppm` and `tolerance` that you specify in `CompareSpectraParam` will **only** be used in the comparison of the precursor m/z of the two spectra, but will **not** be considered by `msentropy_similarity()`!

```r
system.time(
    b <- msentropy::msentropy_similarity(peaksData(exp.spectra)[[1]],
                                         peaksData(lib.spectra)[[1]],
                                         ms2_tolerance_in_da = -1,
                                         ms2_tolerance_in_ppm = 5)
)
   user  system elapsed 
  0.011   0.001   0.012 
b
[1] 0.8409724
```

so, you see the calculated score is **different**! To configure ppm and tolerance with *msentropy* you need to use the `ms2_tolerance_in_da` and `ms2_tolerance_in_ppm` paramters and pass these to `CompareSpectraParam()`

```r
csp <- CompareSpectraParam(
    MAPFUN = joinPeaksNone,
    tolerance = 0,
    ppm = 5,
    FUN = msentropy::msentropy_similarity,
    requirePrecursor = TRUE,
    requirePrecursorPeak = FALSE,
    THRESHFUN = function(x) which(x >= 0.5),
    toleranceRt = Inf,
    percentRt = 0,
    ms2_tolerance_in_da = -1,
    ms2_tolerance_in_ppm = 5
)

system.time(
    d <- matchSpectra(exp.spectra,
                      lib.spectra,
                      param = csp,
                      rtColname = c("rtime", "rtime"),
                      BPPARAM = SerialParam(),
                      addOriginalQueryIndex = TRUE)
)
d$score
[1] 0.8409724
```

I hope this fixes your problems @cbroeckl - I will also go again through the documentation we have to clearly describe that `joinPeaksNone()` must be used, and that different parameters have to be used to configure *msentropy*.
