### ISSUE TITLE
Add Rle utils to MsCoreUtils?

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsCoreUtils#15]
I started implementing the `ChromBackendDataFrame` class in the `Chromatograms` package and also there I think it would make much sense to use the `Rle`-based *compression* we have in `Spectra`.

If you agree @sgibb and @lgatto I would identify some potential candidate functions to move.

**Comment by lgatto** [comment]
Yes, that makes sense to me.

**Comment by sgibb** [comment]
I think it would be useful to share these function I don't like that `MsCoreUtils` will depend on `S4Vectors` and `IRanges` (please don't understand me wrong: these are well maintained packages with a high code quality but it would be the first external dependency of our slim `MsCoreUtils`).

**Comment by jorainer** [comment]
I understand that @sgibb - I'm afraid we will not get around `S4Vectors`, but I will try to avoid the dependency on `IRanges`.
