### ISSUE TITLE
 Normalized spectral angle

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/MsCoreUtils#29]
distance measurement requested by @tobiasko

@tobiasko: could you please link an article with mathematical details here?

**Comment by tobiasko** [comment]
Sure!

Toprak, U. H., Gillet, L. C., Maiolica, A., Navarro, P., Leitner, A., & Aebersold, R. (2014). Conserved peptide fragmentation as a benchmarking tool for mass spectrometers and a discriminating feature for targeted proteomics. Molecular & Cellular Proteomics : MCP, 13(8), 2056–2071. http://doi.org/10.1074/mcp.O113.036475

and maybe

Gessulat, S., Schmidt, T., Zolg, D. P., Samaras, P., Schnatbaum, K., Zerweck, J., et al. (2019). Prosit: proteome-wide prediction of peptide tandem mass spectra by deep learning. Nature Methods, 537(6), 347. http://doi.org/10.1038/s41592-019-0426-7

for an application and extension of normalized spectral angle (SA).

The topic of distance measures also touches spectrum transformation. (normalisation). Is there something planed/implemented? I see some connections to `scale(...)` in base R.

**Comment by tobiasko** [comment]
Cold be nicely used for `.plotMirrorSpectra(...)`, but are you sure it belongs to `MSCoreUtils` @sgibb? Maybe `Spectra` is a better place?

**Comment by sgibb** [comment]
Closed via d9cf17a938cbee9976e9c692b61d61fc32ea741d.
