### ISSUE TITLE
vapply wrapper

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/MsCoreUtils#3]
I am very lazy. To avoid typing `vapply(x, fun, double(1), USE.NAMES=FALSE)` I often define the following wrapper:
```r
vapply1d <- function(X, FUN, ..., USE.NAMES=FALSE) {
    vapply(X=X, FUN=FUN, FUN.VALUE=NA_real_, ..., USE.NAMES=USE.NAMES)
}
```

Then I can just write, e.g. `vapply1d(x, sum)`. There is also a `vapply1l` (logical) and so on.

What do you think about this specific wrapper and helpers like this in general (because they are not MS-related/specific)?

If you think `MsCoreUtils` is the right place for it I am happy to create a PR.

**Comment by jorainer** [comment]
I'm fine with this.

**Comment by sgibb** [comment]
We don't need this function in `MsCoreUtils` very often. If we don't export it we are forced to use `MsCoreUtils:::vapply1d` in e.g. `Spectra` which yield `NOTE`s in `R CMD check`.
If we always import `MsCoreUtils` we can export every function without cluttering the global namespace.
As far as I understood this package it should be the common core of all our packages and it is not meant to be loaded by the user by `library`.

Another function would be the `logging` function to ensure that we use the same date format in every package.

**Comment by lgatto** [comment]
Ok, I thought it would be used inside `MsCoreUtils`. Then it should be exported of course. 

As for logging, I would rather suggest a `loggingMessage(msg, ..., data = TRUE)` function that produces a standardised logging message, and then other packages can create they own logging function for their objects/slots reusing that one.
