### ISSUE TITLE
Should normalise and impute come in MsCoreUtils

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsCoreUtils#36]
I am wondering if we should have low-level functions such as [impute](https://github.com/lgatto/MSnbase/blob/master/R/imputation.R#L7-L111) (currently only in `MSnbase`) and normalize (currently in [`Features`](https://github.com/rformassspectrometry/Features/blob/master/R/Features-processing.R#L3-L34) and [`MSnbase`](https://github.com/lgatto/MSnbase/blob/16286799b16c58a4644a879c7174b874a610746d/R/functions-MSnSet.R#L18-L54)) that work on matrices in `MsCoreUtils`. I think the answer is clearly yes if they would be used in other *RforMassSpectrometry* packages (for instance normalise could be applied to `Spectra`, albeit with its [own implementation](https://github.com/lgatto/MSnbase/blob/fc81f664baa1bbd5b5aaeb2127666fce82824c97/R/functions-Spectrum.R#L284-L294)), but otherwise, I am not sure if it's worth. If yes, this would lead to quite a few new additions to Suggests. 

What do you think @sgibb @jorainer ?

**Comment by jorainer** [comment]
I think it might be helpful to have imputation functions that work on matrices (or also normalization functions) - I have some imputation functions in `xcms` that I could move here. This would help to reduce repeated implementations (and code duplications). For imputation functions I would suggest that these functions all start with `impute...` - I would opt against having a single `impute` function/method that provides all different functions.

**Comment by lgatto** [comment]
Ok to move a simple imputation function to `MsCoreUtils` - I'll do that. 

However, I am not sure I'm keen on having a single function. If you look at the code of the current [`impute_matrix` function](https://github.com/rformassspectrometry/Features/blob/master/R/imputation.R#L209-L290), what you consider being `impute_knn` would simply call `impute::impute.knn`, `impute_MinDet` would simply be a call to `imputeLCMD::impute.MinDet`, ... and so on for most imputation methods. Would we then consider having methods for each of those for the respective classes? Or a single impute method that re-implements the current `impute_matrix`? 

I have the feeling what you suggest would be a better fir for an imputation package that provides a single interface and consistently named functions for various imputation methods.

**Comment by jorainer** [comment]
I was more thinking in similar terms than what we did for the spectra comparison and peak matching. There we have individual functions for each different method. This makes obviously no sense here if there are already functions defined in e.g. the `impute` and `imputeLCMD` packages. So, moving the `impute_matrix` function seems reasonable to me - I could then add the imputation functions from `xcms` I mentioned as options for parameter `"method"`.

**Comment by lgatto** [comment]
Ok, thanks. 

There are cases that match exactly what you refer to: there's currently `imp_neighbour_avg` and I think I will add `impute_mixed` as a separate function.

**Comment by lgatto** [comment]
Here's another question related to this issue.

We will have a `MsCoreUtils::impute_na_matrix()` function and `Features::impute,Features`, `Features::impute,SummarizedExperiment`. What should we do in terms of documentation? The actual functions that does the work will be the former, hence why detailed documentation is required, but users will be exposed to the methods in `Features`.

1. Either we put all the details in `MsCoreUtils::impute_na_matrix()` and point to that man page in `Features`,
2. or the documentation is duplicated. 

I somehow prefer 2, as I think users should get direct and quick access to what is most important and relevant to them, at the cost of documentation duplication (which by the way has been stable for quite some time in `MSnbase`). 

To give you an idea, [here](https://rformassspectrometry.github.io/Features/reference/impute.html)'s how the man page looks at the moment.

**Comment by jorainer** [comment]
I would put a detailed description into `MsCoreUtils::impute_na_matrix` and a brief one in `Features` with a *details in ...*.

**Comment by lgatto** [comment]
PR #40 add imputation functions.

**Comment by lgatto** [comment]
PR #41 adds the normalisation function.
