### ISSUE TITLE
Submitted to Bioconductor

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsCoreUtils#49]
See https://github.com/Bioconductor/Contributions/issues/1432

**Comment by jorainer** [comment]
Thanks @lgatto ! Let me know if you need something.

**Comment by lgatto** [comment]
See here for review comments: https://github.com/Bioconductor/Contributions/issues/1432#issuecomment-609104438

**Comment by lgatto** [comment]
See PR #50

**Comment by lgatto** [comment]
Good news, the [package has been accepted](https://github.com/Bioconductor/Contributions/issues/1432#issuecomment-617022931). :-)

**Comment by lgatto** [comment]
For completeness, copied [from the issue](https://github.com/Bioconductor/Contributions/issues/1432#issuecomment-617040446):

The master branch of your GitHub repository has been added to Bioconductor's git repository.

To use the git.bioconductor.org repository, we need an 'ssh' key to associate with your github user name. If your GitHub account already has ssh public keys (https://github.com/lgatto.keys is not empty), then no further steps are required. Otherwise, do the following:
 
1. [Add an SSH key to your github account](https://help.github.com/articles/connecting-to-github-with-ssh/)
2. [Submit your SSH key to Bioconductor](https://git.bioconductor.org/BiocCredentials/)
 
See further instructions at
 
https://bioconductor.org/developers/how-to/git/
 
for working with this repository. See especially
 
https://bioconductor.org/developers/how-to/git/new-package-workflow/
https://bioconductor.org/developers/how-to/git/sync-existing-repositories/
 
to keep your GitHub and Bioconductor repositories in sync.
 
Your package will be included in the next nigthly 'devel' build (check-out from git at about 6 pm Eastern; build completion around 2pm Eastern the next day) at
 
https://bioconductor.org/checkResults/
 
(Builds sometimes fail, so ensure that the date stamps on the main landing page are consistent with the addition of your package). Once the package builds successfully, you package will be available for download in the 'Devel' version of Bioconductor using `BiocManager::install("MsCoreUtils")`. The package 'landing page' will be created at
 
https://bioconductor.org/packages/MsCoreUtils
 
If you have any questions, please contact the bioc-devel mailing list (https://stat.ethz.ch/mailman/listinfo/bioc-devel); this issue will not be monitored further.
