### ISSUE TITLE
Utility functions for Spectra

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/MsCoreUtils#51]
Hi all,

based on some old `MSnbase` based code I have some functions that might be useful. I use them to search for specific motifs in fragmentation data, e.g. if a certain neutral loss or fragment ion is present. Basically, the functions return `TRUE` or `FALSE` if a certain neutral loss was found or if one or more fragment ions were found.
Would this be of interest for `MsCoreUtils`?

**Comment by jorainer** [comment]
I think that would be great! It would take a `numeric` of m/z values and return `TRUE` or `FALSE`?

**Comment by michaelwitting** [comment]
Yes. Shall it take the m/z's directly or a Spectra object?

**Comment by jorainer** [comment]
Just a `numeric` with m/z values, no `Spectra` object. The *CoreUtils* packages should just contain functions that operate on base R classes (and return base R classes), no S4 objects - that way we ensure that the functions can also be reused in other packages.

**Comment by michaelwitting** [comment]
Okay... I will fork and make a PR or shall I start a branch `devel_michael`. Whatever you prefer...

**Comment by jorainer** [comment]
Ideally a fork and a PR.

**Comment by michaelwitting** [comment]
Alternatively, shall it accept a `PeaksMatrix`? Then there could be an additional check if found m/z is above a certain treshold?

**Comment by jorainer** [comment]
Yes, sure, if you need/use intensity values then that makes total sense (see eventually also the [dotproduct](https://github.com/rformassspectrometry/MsCoreUtils/blob/master/R/dotproduct.R) function that also takes a `matrix` as input).
