### ISSUE TITLE
common returns TRUE even if parameter table is empty

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsCoreUtils#55]
`common` returns always `TRUE` if parameter `table` is empty:

```r
library(MsCoreUtils)
common(4, 1:4, tolerance = 0)
[1] TRUE

common(4, c(), tolerance = 0)
[1] TRUE
```

I'd suggest to include a small `if (!length(table)) rep(FALSE, length(x))`

**Comment by lgatto** [comment]
Yes, I agree.

**Comment by sgibb** [comment]
This has to be fixed in `closest` (which will fix this bug, too). `closest` aims to be a relaxed `match` so the output should be comparable:
```r
closest(4, c())
# [1] 1

match(4, c())
# [1] NA
```
