### ISSUE TITLE
Potential bug in closest?

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsCoreUtils#61]
@sgibb we have `tolerance <- rep_len(tolerance, ntable) + ppm(table, ppm) +` in the `closest` function (see [here](https://github.com/rformassspectrometry/MsCoreUtils/blob/cfbbb0c6de25eeb8a258a4600888bb9135283311/R/matching.R#L109)) but as far as I remember the idea was that we would support `tolerance` to be of length 1 or equal `length(table)` but then this line should be `tolerance <- tolerance + ppm(table, ppm) + ...` instead. Can you please cross-check?

**Comment by sgibb** [comment]
You are right. I won't consider it a bug but it allows the user to apply a `tolerance` argument of any length. 
I will ensure that just 1 or `length(table)` is allowed.
