### ISSUE TITLE
Switch from travis CI to github actions

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsCoreUtils#70]

**Comment by jorainer** [comment]
I get a strange error in the github actions related to pkgdown. I'm wondering if this could be fixed by cleaning the *gh-pages* branch - but I'm afraid that that way we loose our favicon. @sgibb , any idea?

**Comment by sgibb** [comment]
Ok, seems to be a problem with the new `knitr` version. Thanks for moving to gh actions! 
I assume the problem with `pkgdown` is gone?

**Comment by jorainer** [comment]
Yep. I had to manually edit the `_pkgdown.yml` file to add the missing link to the `rla` function. Not ideal that this has to be done manually - but OK.
