### ISSUE TITLE
formatRt() function

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/MsCoreUtils#75]
The `MSnbase::formatRt()` function is quite handy to format retention times from seconds (numeric) to/from a `mm:ss` character. 

Ok to move it to `MsCoreUtils` @jorainer @sgibb ?

**Comment by jorainer** [comment]
Sure, OK for me.

**Comment by lgatto** [comment]
See PR #76

**Comment by sgibb** [comment]
To be honest I don't like that the function called `format` but converts rt in a way that depends on the type of its input.

What about two functions named e.g. `rt2character` and `rt2numeric`.

**Comment by lgatto** [comment]
`formatRt()` has been transferred from `MSnbase` and I feel inclined to keep it. I think it is just simple from a user perspective but I appreciate that from a developer's perspective,  `rt2character()` and `rt2numeric()` are more straight to the point. 


We could have `rt2character()` and `rt2numeric()` and let `formatRt()` use these, with an error if the input is anything but a numeric or a character (as per your comment in #76).

**Comment by lgatto** [comment]
See PR #77 for the suggestion above.
