### ISSUE TITLE
FR: first or last element of a logical vector

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/MsCoreUtils#85]
Similar to `which.min`, `which.max` we need some `which.first`, `which.last` (or just `first`/`last`?) functions that are faster than `tail(lgl, 1)` or `w <- which(lgl); w[length(w)]`. (I guess a C implementation ala `for (int i = n; i >= 0; --i) { if (lgl[i]) return(i); }` would do it.

**Comment by jorainer** [comment]
Regarding the name: I think using `which` in the name makes clear that the returned value is an `integer`.
