### ISSUE TITLE
Problem using join_gnps with compareSpectra

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/MsCoreUtils#87]
Using `join_gnps` with `compareSpectra` throws an error "Error in x[, 1L] : incorrect number of dimensions". Here an example:
```
# load required libraries ------------------------------------------------------
library(Spectra)
library(MsCoreUtils)

# parameter setup --------------------------------------------------------------
tolerance = 0.1
ppm = 0

# test data (multiple matches) -------------------------------------------------
spd <- DataFrame(
  msLevel = c(2L, 2L))

## Assign m/z and intensity values.
spd$mz <- list(
  c(10,26,36,63,91,93),
  c(10,12,24,50,63,105))
spd$intensity <- list(
  c(14,10,15,999,650,1),
  c(35,5,10,16,999,450))

sps <- Spectra(spd)
sps

# compare spectra --------------------------------------------------------------
compareSpectra(sps,
               MAPFUN = MsCoreUtils::join_gnps,
               tolerance = tolerance,
               ppm = ppm)
```

**Comment by jorainer** [comment]
You should not use the *basic* mapping functions from `MsCoreUtils` (i.e. `join` or `join_gnps`) with `compareSpectra` but `joinPeaks` or `joinPeaksGnps` from the `Spectra` package. They ensure that the mapping results are passed along correctly to the similarity calculation function. I'll update the documentation on `compareSpectra` to make that more clear.

**Comment by michaelwitting** [comment]
Well, well... shows again that in most cases the error sits in front of the PC.
Thank you very much!
