### ISSUE TITLE
closest not working with negative m/z values

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsCoreUtils#94]
With positive values all works fine:

```r
library(MsCoreUtils)
a <- c(35, 36, 37)
closest(36.01, a, tolerance = 0.1)
[1] 2

closest(36.00036, a, tolerance = 0, ppm = 15)
[1] 2
```

But with negative ones we fail to detect the match with `ppm`:

```r
closest(-36.01, sort(-a), tolerance = 0.1)
[1] 2

closest(-36.00036, sort(-a), tolerance = 0, ppm = 15)
[1] NA
```

This might in fact just be a missing `abs` somewhere within the code.

**Comment by lgatto** [comment]
Rather than a missing `abs()`, shouldn't this rather throw an error due to negative M/Z values?

**Comment by jorainer** [comment]
I would like to support also negative m/z values - this comes from the idea of the *neutral loss* spectra where the fragment peaks' m/z values are substracted from the precursor m/z (i.e. the m/z reported in the resulting spectra are precursor m/z - fragment m/z). It can happen that the fragment m/z is larger than the precursor m/z and in these cases the resulting m/z would be negative.

Apart, I think the `closest` should not only work for m/z values but any type of values, also negative ones.
