### ISSUE TITLE
How to populate imputation fields ($nNA and randna values)

### ISSUE THREAD

**Issue by AnnaTribe** [rformassspectrometry/MsCoreUtils#96]
I am attempting to use MSnSet to perform imputation on some of my mass spectrometry data and I wondered if you could answer a question I have. Can you please explain how the imputation fields are populated, specifically where the $nNA and randna values come from?

**Comment by lgatto** [comment]
1. The way missing values will be populated (imputed) depends on the imputation method. Please read the [manual page](https://rformassspectrometry.github.io/MsCoreUtils/reference/imputation.html) for details. 
2. `randna` is an argument for the mixed imputation method. Again, please read the manual page for details. 
3. I'm not sure what you mean by `$nNA` - please provide an example or additional details.

**Comment by lgatto** [comment]
Before closing the issue (but feel free to re-open), I advise to use [QFeatures](https://rformassspectrometry.github.io/QFeatures/) objects as a replacement for MSnSets.
